/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package qlquancaphe.view;

import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import java.util.List;
import javax.swing.ImageIcon;
import qlquancaphe.DAO.DonHangDAO;
import qlquancaphe.DAO.ThanhToanDAO;
import qlquancaphe.DAO.ThongTinNHDAO;
import qlquancaphe.TinhTien;
import qlquancaphe.entity.ThongTinNH;

/**
 *
 * @author ADMIN
 */
public class ChuyenKhoan extends javax.swing.JDialog {

    ThongTinNHDAO ttDAO = new ThongTinNHDAO();
    DonHangDAO dhDAO = new DonHangDAO();
    ThanhToanDAO thanhToanDAO = new ThanhToanDAO();
    public int amount;

    /**
     * Creates new form ChuyenKhoan
     */
    public ChuyenKhoan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    public void setSoTien(int amount) {
        this.amount = amount;
    }

    void init() {
        TinhTien ttien = new TinhTien();
        int soTien = ttien.getSoTien();
        String hinh = "https://img.vietqr.io/image/";
        String tenNH = "";
        String dauTru = "-";
        String stk = "";
        String nd = "compact2.jpg?amount=";
        String nd1 = "&addInfo=THANKS%20YOU&accountName=";
        String nd2 = "";

        List<ThongTinNH> list = ttDAO.selectAll();
        for (ThongTinNH tt : list) {
            tenNH = tt.getTenNH();
            stk = tt.getStk();
            nd2 = tt.getChuTK();
            String nd3 = nd2.replace(" ", "%20");
            String hinhHoanChinh = hinh + tenNH + dauTru + stk + dauTru + nd + soTien + nd1 + nd3;
            try {
                URL imageUrl = new URL(hinhHoanChinh);
                ImageIcon imageIcon = new ImageIcon(imageUrl);

                Image image = imageIcon.getImage();
                int width = 480;
                int height = 480;
                Image scaledImage = image.getScaledInstance(width, height, Image.SCALE_SMOOTH);

                ImageIcon scaledImageIcon = new ImageIcon(scaledImage);

                lblHinh.setIcon(scaledImageIcon);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHinh = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChuyenKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChuyenKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChuyenKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChuyenKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChuyenKhoan dialog = new ChuyenKhoan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblHinh;
    // End of variables declaration//GEN-END:variables
}
